apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.csi.config.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque

# Use 'stringData' so Helm can store plain text, which Kubernetes will convert to base64.
stringData:
  username: {{ .Values.csi.username | quote }}
  password: {{ .Values.csi.password | quote }}