apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: csi-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--drivername=spectrumscale.csi.ibm.com"
          env:
            - name: CSI_ENDPOINT
              value: "unix:///csi/csi.sock"
            # Additional environment variables needed for your environment
            - name: CLUSTER_ID
              value: "{{ .Values.csi.clusterId }}"
            - name: PRIMARYFS
              value: "{{ .Values.csi.primaryFs }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}

