---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  # Additional RBAC rules required by the driver
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ibm-spectrum-scale-csi-driver.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}

