apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: spectrumscale.csi.ibm.com
parameters:
{{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: "{{ $value }}"
{{- end }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

